### PR TITLE
fix: include stack in browser uncaught error reporting

### LINKED ISSUE #5106: 🐛 Bug: Browser doesn't include call stack for global uncaught errors
### Bug Report Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [X] I want to provide a PR to resolve this

### Expected

When an uncaught error occurs during a test in browsers, you'd expect to see the call stack. That's useful.

```plaintext
Error: Oh no!
    at inner (test.example.js:8:15)
```

### Actual

Mocha's browser error handling code was written before browsers gave nice stacks (https://github.com/mochajs/mocha/commit/eb58761bb3346d2597e8365e60273417127b72c4).

```plaintext
Error: Error: Oh no! (http://127.0.0.1:8081/test.example.js:8)
```

### Minimal, Reproducible Example

Using a minimal browser setup such as in https://github.com/mochajs/mocha-examples/pull/72:

```js
it("example", (done) => {
    function inner() {
        throw new Error("Oh no!");
    }

    setTimeout(inner);
});
```

### Versions

Mocha: 10.3.0

### Additional Info

This was filed long ago in #2167, then a fix proposed in #3952. Since #2167 is quite old, re-filing to be more current.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5106
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md) were taken

## Overview

Continues #3952. In summary, this change uses the "newly" available `err` parameter in `onerror` to log a nicer stack.

Co-authored-by: Peter Rust <peter@cornerstonenw.com>

### CODE REVIEW

File: browser-entry.js [hunk 1]
```diff
@@ -71,8 +71,8 @@ process.listenerCount = function (name) {
 
 process.on = function (e, fn) {
   if (e === 'uncaughtException') {
-    global.onerror = function (err, url, line) {
-      fn(new Error(err + ' (' + url + ':' + line + ')'));
+    global.onerror = function (msg, url, line, col, err) {
+      fn(err || new Error(msg + ' (' + url + ':' + line + ')'));
```
Comment (JoshuaKGoldberg) [inline browser-entry.js:75]: [Feature] Since `col` is now available, I think it'd be nice to include it too:

```suggestion
      fn(err || new Error(msg + ' (' + url + ':' + line + ':' + col + ')'));
```

**Comment by prust** [comment]
thanks @JoshuaKGoldberg!

**Comment by JoshuaKGoldberg** [comment]
...and, re-opening per https://github.com/mochajs/mocha/pull/5080#issuecomment-1978667767. 😄

File: test/unit/throw.spec.js [hunk 2]
```diff
@@ -13,11 +14,13 @@ var STATE_FAILED = Runnable.constants.STATE_FAILED;
 describe('a test that throws', function () {
   var suite;
   var runner;
+  var sandbox;
   var uncaughtHandlers;
 
   beforeEach(function () {
     suite = new Suite('Suite', 'root');
     runner = new Runner(suite);
+    sandbox = sinon.createSandbox();
```
Comment (voxpelli) [inline test/unit/throw.spec.js:23]:
```suggestion
  var uncaughtHandlers;

  beforeEach(function () {
    suite = new Suite('Suite', 'root');
    runner = new Runner(suite);
```

No need to create a sandbox, sinon comes with a default one.

Though, should add:

https://github.com/mochajs/mocha/blob/2f3fedcc41cbb9d3e503d84098fcc07d7c3c49f1/test/unit/errors.spec.js#L8-L10

**Review by voxpelli — CHANGES_REQUESTED** [review]
We should go through all the browser polyfilling eventually, but this looks good, only the sinon fix needed.

---

For future reference / personal reference: Related APIs:

* https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event
* https://nodejs.org/api/process.html#event-uncaughtexception

Could perhaps want to move Mocha to this one eventually:

* https://nodejs.org/api/process.html#processsetuncaughtexceptioncapturecallbackfn

**Comment by JoshuaKGoldberg** [comment]
This was released in [`mocha@10.5.0`](https://www.npmjs.com/package/mocha/v/10.5.0). 🚀
