### PR TITLE
fix: use original require() error for TS files if ERR_UNKNOWN_FILE_EXTENSION

### LINKED ISSUE #5393: 🐛 Bug: original require() errors are masked with an unrelated `ERR_UNKNOWN_FILE_EXTENSION`
### Bug Report Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [x] I want to provide a PR to resolve this (but after community discussion first)

### Expected

in 11.7.0, if `require()` fails, the error is thrown and output to console. e.g.:

```
 $ mocha --require ts-node/register --require source-map-support/register 'a.ts'
 
  Exception during run: .../a.ts:61:66 - error TS2345: Argument of type '{ address: string; }' is not assignable to parameter of type ...
 
 $ mocha --version
 11.7.0
```

### Actual

after this change https://github.com/mochajs/mocha/pull/5384#diff-30714d24f4a4acd4826e5f7e92f58922ed0ab41b1f0062ae2a46df6c5c899eb4L93-L102
the `err` is masked and returned an `ERR_UNKNOWN_FILE_EXTENSION` which is misleading. 

```
 $ mocha --require ts-node/register --require source-map-support/register 'a.ts'
 
  Exception during run: TypeError: Unknown file extension ".ts" for /.../a.ts
     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:219:9)
     at defaultGetFormat (node:internal/modules/esm/get_format:245:36)
     at defaultLoad (node:internal/modules/esm/load:120:22)
     at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:580:32)
     at async ModuleJob._link (node:internal/modules/esm/module_job:116:19) {
   code: 'ERR_UNKNOWN_FILE_EXTENSION'
 }
 
 $ mocha --version
 11.7.1
```

### Minimal, Reproducible Example

1. install `ts-node` and require it along with the mocha command i.e. `mocha --require ts-node/register abc.ts`
2. try to run with a giblish ts file. e.g.

```
bla@#&#_@$
```
what ever contents in it causing a ts not compilable will output the same ERR_UNKNOWN_FILE_EXTENSION error

### Versions

11.7.1 not work
11.7.0 works

### Additional Info

I think this is open to discussion whether this should be classified as bug or not, but I just want to point out the breaking behavioral change in this patch version release which might potentially affect people who rely on the error output for debugging purpose or experiencing surprises suddenly.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5393
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Adds in a special-case `try`/`catch` -> `throw`. If the file being imported is a `.cts`, `.mts`, or `.ts` _and_ the caught error from `import()` is for an unknown file extension, we know it's from a Node.js version that doesn't support those file extensions. In that case we'll want to throw the original informative `require()` error per #5393.

💖

### CODE REVIEW

File: lib/nodejs/esm-utils.js [hunk 1]
```diff
@@ -92,9 +92,19 @@ const tryImportAndRequire = async (file, esmDecorator) => {
...
     return require(file);
-  } catch (err) {
-    // Import if require fails.
-    return dealWithExports(await formattedImport(file, esmDecorator));
+  } catch (requireErr) {
+    // Fallback to import() if require() fails.
+    try {
+      return dealWithExports(await formattedImport(file, esmDecorator));
+    } catch (importErr) {
+      // If a --require module throws in a Node.js version that doesn't yet support .ts files,
```
Comment (mark-wiemer) [inline lib/nodejs/esm-utils.js:104]: Maybe we can add tests for a specific range of Node versions? We should have an automated test that enters this branch of code for sure

**Review by mark-wiemer — CHANGES_REQUESTED** [review]

File: lib/nodejs/esm-utils.js [hunk 2]
```diff
@@ -92,9 +92,19 @@ const tryImportAndRequire = async (file, esmDecorator) => {
...
+      // the fallback import() will throw an uninformative error about the file extension.
+      // What we actually care about is the original require() error.
+      // See: https://github.com/mochajs/mocha/issues/5393
+      throw /\.(?:c|m)?ts$/.test(file) || importErr?.code === "ERR_UNKNOWN_FILE_EXTENSION"
```
Comment (mark-wiemer) [inline lib/nodejs/esm-utils.js]: Regex is already weird enough, I'm in favor of minor repetition if it supports clarity

```suggestion
      throw /\.(cts|mts|ts)$/.test(file) || importErr?.code === "ERR_UNKNOWN_FILE_EXTENSION"
```

File: lib/nodejs/esm-utils.js (hunk 1 above)
Comment (JoshuaKGoldberg) [reply lib/nodejs/esm-utils.js:104]: (discussed 1:1) Agreed. It really hurts me not covering this behavior with tests 🙃. We'll block this on ~~#5407~~ #5417: once that lands, I can add an integration/similar test for a specific Node.js version or two.

Comment (mark-wiemer) [reply lib/nodejs/esm-utils.js:104]: Ref also #5413 which also adds an if-else here and adds tests for the new branch

File: lib/nodejs/esm-utils.js [hunk 3]
```diff
@@ -101,17 +101,35 @@ const requireModule = async (file, esmDecorator) => {
...
   }
 };
 
 // We only assign this `requireOrImport` function once based on Node version
 // We check for file extensions in `requireModule` and `tryImportAndRequire`
-debug('assigning requireOrImport, require_module === %O', process.features.require_module);
+debug(
+  'assigning requireOrImport, require_module === %O',
+  process.features.require_module
+);
```
Comment (JoshuaKGoldberg) [inline lib/nodejs/esm-utils.js]: Prettier did this. 🤷

Comment (mark-wiemer) [reply lib/nodejs/esm-utils.js]: I have `editor.formatOnSave: false` for this reason, but I'm totally OK with formatting files like this on smaller PRs :)

File: test/node-unit/esm-utils.spec.js [hunk 4]
```diff
@@ -20,6 +20,21 @@ describe('esm-utils', function () {
...
+            '../../test/node-unit/fixtures/broken-syntax.ts'
+          ),
+        'to be rejected with error satisfying',
+        {
+          name: 'SyntaxError',
+          message:
+            /Invalid or unexpected token|Expected ident/
+        }
+      );
+    });
```
Comment (JoshuaKGoldberg) [inline test/node-unit/esm-utils.spec.js:37]: If `esm-utils.js` is reset to `main`, this fails in Node.js 20:

```plaintext
joshgoldberg ~/repos/mocha $ node --version; node bin/mocha.js test/node-unit/esm-utils.spec.js
v20.19.2


  esm-utils
    requireOrImport
      ✔ should show an informative error message for a broken default import
      1) should show a syntax error message when importing a TypeScript file with invalid syntax
    loadFilesAsync()
      ✔ should not decorate imported module if no decorator passed
      ✔ should decorate imported module with passed decorator


  3 passing (23ms)
  1 failing

  1) esm-utils
       requireOrImport
         should show a syntax error message when importing a TypeScript file with invalid syntax:
     
expected
() =>
  esmUtils.requireOrImport(
    '../../test/node-unit/fixtures/broken-syntax.ts'
  )
to be rejected with error satisfying { name: 'SyntaxError', message: /Invalid or unexpected token|Expected ident/ }
  expected Promise (rejected) => TypeError({ message: 'Unknown file extension ".ts" for /Users/josh/repos/mocha/test/node-unit/fixtures/broken-syntax.ts', code: 'ERR_UNKNOWN_FILE_EXTENSION' })
  to be rejected with error satisfying { name: 'SyntaxError', message: /Invalid or unexpected token|Expected ident/ }
    expected TypeError({ message: 'Unknown file extension ".ts" for /Users/josh/repos/mocha/test/node-unit/fixtures/broken-syntax.ts', code: 'ERR_UNKNOWN_FILE_EXTENSION' }) to satisfy { name: 'SyntaxError', message: /Invalid or unexpected token|Expected ident/ }

    {
      message: 'Unknown file extension ".ts" for /Users/josh/repos/mocha/test/node-unit/fixtures/broken-syntax.ts', // should match /Invalid or unexpected token|Expected ident/
      code: 'ERR_UNKNOWN_FILE_EXTENSION',
      name: 'TypeError' // should equal 'SyntaxError'
                        //
                        // TypeError
                        // SyntaxError
    }

      at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:189:9)
      at defaultGetFormat (node:internal/modules/esm/get_format:232:36)
      at defaultLoad (node:internal/modules/esm/load:145:22)
      at async ModuleLoader.loadAndTranslate (node:internal/modules/esm/loader:477:45)
      at async ModuleJob._link (node:internal/modules/esm/module_job:110:19)
  From previous event:
      at Context.<anonymous> (test/node-unit/esm-utils.spec.js:25:14)
      at callFn (lib/runnable.js:366:21)
      at Runnable.run (lib/runnable.js:354:5)
      at Runner.runTest (lib/runner.js:719:10)
      at /Users/josh/repos/mocha/lib/runner.js:842:12
      at next (lib/runner.js:634:14)
      at /Users/josh/repos/mocha/lib/runner.js:644:7
      at next (lib/runner.js:527:14)
      at Immediate.<anonymous> (lib/runner.js:612:5)
      at process.processImmediate (node:internal/timers:483:21)
      set UNEXPECTED_FULL_TRACE=true to see the full stack trace
```

**Comment by JoshuaKGoldberg** [comment]
cc @mark-wiemer - none of the test failures are unique to this PR. I filed #5467.

File: test/node-unit/esm-utils.spec.js (hunk 4 above)
Comment (mark-wiemer) [reply test/node-unit/esm-utils.spec.js:37]: This might be the "underlying error message" referenced in #5452 as well

**Review by mark-wiemer — APPROVED** [review]
