### PR TITLE
--forbid-only and --forbid-pending now handle suites properly

### LINKED ISSUE #2944: `--forbid-only` does not error on suite marked `only` with no tests
Both before and after #2874, the `--forbid` functions are implemented in terms of tests, whereas `only` is quite aware of suites including empty ones; thus, the following file:
```js
describe.only("nothing", function() {})
it("should fail", function() { throw new Error("Ouch!") })
```
...passes with 0 tests run instead of failing due to `only` being forbidden (or ignoring the empty `only`ed suite and failing the other test).

### PR DESCRIPTION
**Pull request by outsideris**
### Description of the Change
As #2944 , `--forbid-only` didn't catch an empty suite that marked as only because checking `forbidOnly` is happened in [`runTest`](https://github.com/mochajs/mocha/blob/master/lib/runner.js#L435).

So, I added `forbidOnly` check in `runSuite` when there is no greped tests and there are `_onlySuites`. To run `forbidOnly` check in `runTest`, I made new empty test here.

### Alternate Designs
Not delegate `runTest` for `forbidOnly`,  throw forbid error in `runSuite`?

### Why should this be in core?
If there is an empty suite that marked only, tests will be passed with `--forbid-only` option.

### Possible Drawbacks
If I added an empty test with no title, there is no test name in output. It looks a little bit weired. Any idea?

```
  nothing
    1)


  0 passing (3ms)
  1 failing

  1) nothing
       :
     Error: `.only` forbidden
      at Runner.runTest (lib/runner.js:436:8)
      at /Users/outsider/Dropbox/projects/github/mocha/lib/runner.js:568:12
      at next (lib/runner.js:364:14)
      at /Users/outsider/Dropbox/projects/github/mocha/lib/runner.js:374:7
      at next (lib/runner.js:298:14)
      at Immediate._onImmediate (lib/runner.js:342:5)
```
### Applicable issues
close #2944

### CODE REVIEW

**Comment by plroebuck** [comment]
> If there is an empty suite that marked only, tests will be passed with --forbid-only option.

Don't follow you. If the suite is empty, then there are no tests to run -- therefore, none will pass or fail.

**Comment by plroebuck** [comment]
See additional comments in #2944.

File: lib/runner.js [hunk 1]
```diff
@@ -633,6 +634,16 @@ Runner.prototype.runSuite = function(suite, fn) {
 
   debug('run suite %s', suite.fullTitle());
 
+  if (!total && this.forbidOnly && hasOnly(suite)) {
```
Comment (boneskull) [inline lib/runner.js]: why `!total`?

File: lib/runner.js [hunk 2]
```diff
@@ -633,6 +634,16 @@ Runner.prototype.runSuite = function(suite, fn) {
...
+    suite._onlySuites.forEach(function(onlySuite) {
```
Comment (boneskull) [inline lib/runner.js]: I really don't love this... it seems like a pretty gnarly hack. 😐 	 I'll see if I can find a more elegant alternate implementation.

**Comment by boneskull** [comment]
@outsideris please see this implementation and tell me what you think:

https://github.com/boneskull/mocha/commit/8a929c54f9d964fcc97e503ae4b43e1ba81cd55f

(if you push your branches to mochajs/mocha instead of your fork, we can collaborate easily)

File: lib/runner.js (hunk 1 above)
Comment (outsideris) [reply lib/runner.js]: Because non-empty suite already checked in `runTest`.

**Comment by outsideris** [comment]
I also feel my approach is good. I will check your implement.

**Comment by boneskull** [comment]
my implementation will fail as soon as the `suite.only` is encountered, before running any tests.  it doesn't make sense to me to continue processing suites if we know we will fail.

**Comment by outsideris** [comment]
I applied @boneskull 's implementation. Fast-fail is good.
Also, I add code to throw an empty suite marked `.skip` with `--forbid-pending` like `--forbid-only`.  As https://github.com/mochajs/mocha/issues/2944#issuecomment-441851621 , `--forbid-pending` has same bug.

For clearify, output is different between `.only`/`.skip` at suites and test cases.

### `.only`/`.skip` at suites
```js
describe.only("Suite", function() {
  it("should be tested", function() { })
});
```

```sh
$ mocha --forbid-only example.js
/Users/outsider/Dropbox/projects/github/mocha/lib/interfaces/common.js:128
            throw new Error('`.only` forbidden');
            ^

Error: `.only` forbidden
    at Object.create (/Users/outsider/Dropbox/projects/github/mocha/lib/interfaces/common.js:128:19)
    at Object.only (/Users/outsider/Dropbox/projects/github/mocha/lib/interfaces/common.js:95:21)
    at Function.context.describe.only (/Users/outsider/Dropbox/projects/github/mocha/lib/interfaces/bdd.js:67:27)
    at Object.<anonymous> (/Users/outsider/Dropbox/projects/github/mocha/example.js:1:72)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/outsider/Dropbox/projects/github/mocha/lib/mocha.js:287:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/outsider/Dropbox/projects/github/mocha/lib/mocha.js:284:14)
    at Mocha.run (/Users/outsider/Dropbox/projects/github/mocha/lib/mocha.js:718:10)
    at Object.<anonymous> (/Users/outsider/Dropbox/projects/github/mocha/bin/_mocha:642:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

### `.only`/`.skip` at test cases
```js
describe("Suite", function() {
  it.only("should be tested", function() { })
});
```

```sh
$ mocha --forbid-only example.js


  Suite
    1) should be tested


  0 passing (2ms)
  1 failing

  1) Suite
       should be tested:
     Error: `.only` forbidden
      at Runner.runTest (lib/runner.js:436:8)
      at /Users/outsider/Dropbox/projects/github/mocha/lib/runner.js:568:12
      at next (lib/runner.js:364:14)
      at /Users/outsider/Dropbox/projects/github/mocha/lib/runner.js:374:7
      at next (lib/runner.js:295:14)
      at Immediate._onImmediate (lib/runner.js:342:5)
```

**Comment by boneskull** [comment]
awesome.

**Comment by boneskull** [comment]
@outsideris 	you  may want to move the `require('chai')` in `test/reporters/base.spec.js` to the top of the file.  that might address the timeout.

**Comment by outsideris** [comment]
I moved `require('chai')` to the top of the file.
For history, it was discussed in #3527 .

**Comment by boneskull** [comment]
@plroebuck are you still opposed to this idea?
