### PR TITLE
fix extension and spec handling; closes #3808

### LINKED ISSUE #3808: Extension option does not clear the default .js
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [ x Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

According to [Mocha's own docs](https://mochajs.org/#-extension-ext-watch-extensions-ext) one should be able to specify which extensions mocha will automatically load and that by specifying an extension the default of `*.js` should be cleared. _This does not happen in version 6_ (and I have never seen it happen earlier either).

### Steps to Reproduce
```
git clone fatso83/test-driven-learning
cd javascript/mocha-recursive-extensions-test
npm i
npm run test-bar
```

**Expected behavior:** 
Only this output should be shown, by Mocha loading only the file with the `.bar` extension
```
mocha --extension bar

  normal.bar
    ✓ should do nothing but register the test
```

**Actual behavior:** 
It loads the `normal.bar` - _in addition to_ all the files ending in `.js`.
```
mocha --extension bar

This is not a test: no-test.js


  normal.bar
    ✓ should do nothing but register the test

  normal.bar.js
    ✓ should do nothing but register the test

  normal.js
    ✓ should do nothing but register the test
```

**Reproduces how often:** 
Always

### Versions

6.0.2

### PR DESCRIPTION
**Pull request by boneskull**
Also fixes some issues in the options unit tests and adds coverage around `spec` handling.

This needs some manual testing, as I had to monkey with `watch` a bit.

cc @dedene

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -575,9 +575,15 @@ exports.lookupFiles = function lookupFiles(filepath, extensions, recursive) {
...
-    } else {
+    // check all extensions
+    if (
+      !extensions.some(function(ext) {
+        if (fs.existsSync(filepath + '.' + ext)) {
+          filepath += '.' + ext;
+          return true;
+        }
+      })
+    ) {
```
Comment (plroebuck) [inline lib/utils.js]: The _only_ reason this was here was to allow the historical usage of "test.js" via the default spec "test". IMO, we should **not** propagate this further.

The "Handle directory" code below already handles extensions for "test/*".

File: lib/cli/options.js [hunk 2]
```diff
@@ -10,7 +10,8 @@ const fs = require('fs');
 const yargsParser = require('yargs-parser');
 const {types, aliases} = require('./run-option-metadata');
 const {ONE_AND_DONE_ARGS} = require('./one-and-dones');
-const mocharc = require('../mocharc.json');
+// paranoia
+const mocharc = Object.freeze(require('../mocharc.json'));
```
Comment (plroebuck) [inline lib/cli/options.js]:
```js
const rcDefaults = Object.freeze(require('../mocharc.json'));
```

File: lib/cli/options.js [hunk 3]
```diff
@@ -321,14 +322,38 @@ const loadOptions = (argv = []) => {
...
+  // special case: "extension" option should not combine with default value.
+  // normally we want to combine "array"-type options, and we _do_ with "extension", but only
+  // within user-defined configuration (args or anything else).
+  // we must also search through any aliases of "extension" because while the arguments are ///
+  // normalized by this point, the config file values are not.
+  // only the "canonical" option name is used in `mocharc`, so we needn't worry about clearing
+  // multiple options.
+  // NOTE: as of this writing, "extension" is the only default value which is of an "array" type;
+  // it's unknown whether the the below strategy should be generalized to any other future
+  // "array"-type default option.
```
Comment (plroebuck) [inline lib/cli/options.js]: Use [block comment style](https://github.com/airbnb/javascript#comments--multiline) here.

File: lib/cli/options.js [hunk 4]
```diff
@@ -321,14 +322,38 @@ const loadOptions = (argv = []) => {
...
+  const processedMocharc = Object.assign({}, mocharc);
```
Comment (plroebuck) [inline lib/cli/options.js]: Deep clone, or see if this (e.g., ES7 `_.omit`) is supported...
```js
  let key = 'extension';
  const { [key]: _ignore, ...processedMocharc } = mocharc;
```

`Object.assign` here does shallow clone (after shallow freeze).
Surprised the `delete` didn't throw `TypeError`.

**Comment by plroebuck** [comment]
Rebase

**Comment by juergba** [comment]
I think there is a standard yargs way to achieve this, using the "default" option. I just did some short testing, nevertheless it seems to work.
```js
// line 109
const result = yargsParser.detailed(args, {
    default: {extension: ["js"]},      // set default values with "mocharc"
    configuration,
    configObjects,
    coerce: coerceOpts,
    narg: nargOpts,
    alias: aliases,
    string: types.string,
    array: types.array,
    number: types.number,
    boolean: types.boolean.concat(nodeArgs.map(pair => pair[0]))
  });
```
```js
// line 326
args = parse(
    args._,
    args,
    rcConfig || {},
    pkgConfig || {},
    optsConfig || {},
    //mocharc                           don't set default values here
  );
```

**Comment by boneskull** [comment]
@juergba Hmm, you're right.

I think instead of this strategy, I'll change it so that we can still keep the default config in our `lib/mocharc.json`, but use its values as defaults instead of just another config object which is merged in.

**Comment by juergba** [comment]
Also in "lib/cli/run-helpers.js" the default extension of "js" is set hardcoded several times.
i.e. `watchRun()` or `runMocha()`.

**Comment by juergba** [comment]
@boneskull is it ok for you, if I work on this one?

**Comment by boneskull** [comment]
@juergba yes, go ahead

**Comment by plroebuck** [comment]
@juergba second time now you merged without any review (despite prior request to do otherwise) and this time you introduced bug...

**Comment by plroebuck** [comment]
Corrected code...


**"lib/utils.js"**
```js
/**
 * Lookup file names at the given `path`.
 *
 * @description
 * Filenames are returned in _traversal_ order by the OS/filesystem.
 * **Make no assumption that the names will be sorted in any fashion.**
 *
 * @public
 * @memberof Mocha.utils
 * @param {string} filepath - Base path to start searching from.
 * @param {string[]} [extensions=[]] - File extensions to look for.
 * @param {boolean} [recursive=false] - Whether to recurse into subdirectories.
 * @return {string[]} An array of file pathnames.
 * @throws {Error} if no files match pattern.
 * @throws {TypeError} if `filepath` is directory and `extensions` not provided or empty.
 */
exports.lookupFiles = function lookupFiles(filepath, extensions, recursive) {
  var files = [];
  var stat;

  if (extensions === undefined) {
    extensions = [];
  }
  if (recursive === undefined) {
    recursive = false;
  }

  if (!fs.existsSync(filepath)) {
    // Check all extensions, using first match found (if any)
    if (
      !(extensions.some(function(ext) {
        var filepathWithExtname = filepath + '.' + ext;
        if (fs.existsSync(filepathWithExtname)) {
          filepath = filepathWithExtname;
          return true;
        }
      })
    ) {
      // Handle glob
      files = glob.sync(filepath);
      if (!files.length) {
        throw createNoFilesMatchPatternError(
          'Cannot find any files matching pattern ' + exports.dQuote(filepath),
          filepath
        );
      }
      return files;
    }
  }

  // ...no further changes to merged code...
}
```

**Comment by juergba** [comment]
@plroebuck 
Yes, without @boneskull contributions to "needs-review"-PRs have been close to null during the last few weeks. There is no one stepping into his gap, that's worrying.

`you introduced bug...`  can you be more ... specific?

`corrected code`: this is the solution @boneskull already proposed, so nothing new. It only uses the first match of `filepath + '.' + ext` and ignores the rest of matches. I wonder why this should be correct.

**Comment by juergba** [comment]
> As I commented originally in his PR [...]

You are right, a directory named "test.js" will fail. I will open a PR and use your proposition. I don't agree completely, though. With two files (eg. "unit.ts" and "unit.js") a call "unit" plus extension: ['ts', 'js'] should return both files, not just some/the first one.
I will also have to check wether the glob always returns files.

> True, but almost no PRs here [...]

I can live with that procedure.

**Comment by plroebuck** [comment]
> You are right, a directory named "test.js" will fail. I will open a PR and use your proposition. I don't agree completely, though. With two files (eg. "unit.ts" and "unit.js") a call "unit" plus extension: ['ts', 'js'] should return both files, not just some/the first one.

The `filepath + '.js'` _hack_ was **never** intended to handle what you're trying to do with it. Its purpose was to allow small packages that only exported a couple functions (typically from "index.js") to use "test.js" to test them.

If a package is exporting functions in more than one language, its specifications _should_ live in the "test" directory -- the simplistic specification scheme above shouldn't apply.
