### PR TITLE
properly dispose Mocha instance in watch mode; closes #4495

### LINKED ISSUE #4495: mocha leaks event listeners on `process`
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

`Runner` does not clean up event listeners on global objects.

### Steps to Reproduce

https://github.com/eps1lon/mocha-event-leak

**Expected behavior:** [What you expect to happen]

Removes all event listeners when destroyed.

**Actual behavior:** [What actually happens]

Event listeners on `process` leak:
```bash
ℹ [mocha] waiting for changes...
(node:18921) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18921) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
```

`Runner.prototype.dispose` is never called in watchmode.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time after the ~10th run

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`: 14.4.0
- Your operating system
  - name and version: Ubuntu 18.04
  - architecture (32 or 64-bit): 64  bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): fish
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): no
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): no

### Additional Information

The event handlers are attempted to be removed in `prepare`:https://github.com/mochajs/mocha/blob/7e490aa13e8ed25c78e77faa6fed0337e948b619/lib/runner.js#L1063-L1064
That doesn't have any effect after instantiation since `this.uncaught` is different between each runner instance. Whatever constructs the `Runner` instance also needs to call `dispose`. Might be better if the `Runner` took care of it e.g. with `this.once('end', () => this.dispose())` in the `constructor`.

### PR DESCRIPTION
**Pull request by boneskull**
- Mocha instance needed a `dispose()` call before re-instantiation
- Exposed `sleep()` in integration test helpers

Ref: #4495

### CODE REVIEW

File: test/integration/helpers.js [hunk 1]
```diff
@@ -415,8 +415,12 @@ async function runMochaWatchAsync(args, opts, change) {
   if (typeof opts === 'string') {
     opts = {cwd: opts};
   }
-  opts = {sleepMs: 2000, ...opts, fork: process.platform === 'win32'};
-  opts.stdio = ['pipe', 'pipe', 'inherit'];
+  opts = {
```
Comment (boneskull) [inline test/integration/helpers.js:418]: this was preventing watch mode tests from examining STDERR

File: test/integration/helpers.js [hunk 2]
```diff
@@ -539,24 +543,25 @@ function sleep(time) {
 module.exports = {
   DEFAULT_FIXTURE,
   SPLIT_DOT_REPORTER_REGEXP,
+  copyFixture,
```
Comment (boneskull) [inline test/integration/helpers.js:546]: sorted this

File: test/integration/options/watch.spec.js [hunk 3]
```diff
@@ -343,5 +345,31 @@ describe('--watch', function() {
...
+      this.timeout(20000);
+      const testFile = path.join(tempDir, 'test.js');
+      copyFixture(DEFAULT_FIXTURE, testFile);
+
+      return expect(
+        runMochaWatchAsync(
+          [testFile],
+          {cwd: tempDir, stdio: 'pipe'},
+          async () => {
+            const iterations = new Array(15);
```
Comment (eps1lon) [inline test/integration/options/watch.spec.js:359]: Might be faster and more robust to set this to `emitter.getMaxListeners() + 1`. Maybe it works by setting the max listener count to a low number e.g. 1 or 2 which should reduce test runtime.

Comment (boneskull) [reply test/integration/options/watch.spec.js:359]: would rather just use the default settings, so yeah, `emitter.getMaxListeners()` sounds better
