### PR TITLE
Fix #4348

### LINKED ISSUE #4348: Hook only renamed when it fails, not when it begins and ends successfully
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

A hook's title is only rewritten to include the test's name when it fails.  This means the name is inconsistent between hook start and hook failure, which is messing up the logging of a custom reporter.  Additionally, the hook name is incomplete when it starts, because it does not include the name of the associated test.

Rewriting is done here: https://github.com/mochajs/mocha/blob/master/lib/runner.js#L419-L432

'hook' event: title = `"before each" hook`
'fail' event: title = `"before each" hook for "name of test case"`, originalTitle = `"before each" hook`

### Steps to Reproduce

Run this reproduction: https://github.com/cspotcode/repros/tree/mocha-hook-title-discrepancy

**Expected behavior:** [What you expect to happen]

Hook's `title` includes the `from "name of test case"` for *all* events.

**Actual behavior:** [What actually happens]

Hook title does not include `from "name of test case"` suffix in 'hook' event and never includes if it succeeds.

**Reproduces how often:** [What percentage of the time does it reproduce?]

all the time

### Versions

- `mocha --version`: N/A, not installed
- `node node_modules/.bin/mocha --version`: 8.0.1
- The output of `node --version`: v14.2.0
- Your operating system
  - name and version: Windows 10, WSL2, running Ubuntu 16.04.6 LTS
  - architecture (32 or 64-bit): 64bit
- Your shell (e.g., bash, zsh, PowerShell, cmd): bash
- Your browser and version (if running browser tests): N/A
- Any third-party Mocha-related modules (and their versions): custom reporter which listens to `hook`, `hook end`, and `fail` events
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): none

### PR DESCRIPTION
**Pull request by cspotcode**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions.

### Description of the Change

Rewrites a hook's title always, instead of only when the hook fails.  Fixes issues described in #4348.

### Alternate Designs

None

### Why should this be in core?

It's a bug as described in #4348

### Benefits

Bug is fixed

### Possible Drawbacks

Any change is potentially breaking, even a bugfix.

### Applicable issues

#4348

* Is this a breaking change (major release)? no
* Is it an enhancement (minor release)? no
* Is it a bug fix, or does it not impact production code (patch release)? yes

### CODE REVIEW

**Comment by cspotcode** [comment]
@boneskull this is ready for review.

File: lib/runner.js [hunk 1]
```diff
@@ -514,8 +502,25 @@ Runner.prototype.hook = function(name, fn) {
       }
       self.emit(constants.EVENT_HOOK_END, hook);
       delete hook.ctx.currentTest;
+      setHookTitle(hook);
```
Comment (juergba) [inline lib/runner.js:505]: What is this for?

Comment (cspotcode) [reply lib/runner.js:505]: When hook.ctx.currentTest is deleted, this changes the hook's title so that it no longer mentions the test case and only mentions the test suite.  It affects the "multiple done calls" errors.

**Comment by cspotcode** [comment]
@juergba it sounds like you're saying that the title rewriting, which mocha is already doing, is bad.  Do you want to submit an alternative PR which fixes that?  Do we know why the current rewriting behavior was implemented?

**Comment by juergba** [comment]
No, not bad. When a hook fails, normally no more related tests are executed. E.g. when a `beforeAll` hook fails, all corresponding tests "disappear".  Renaming such a failing hook is a different thing than renaming all hooks. It's easier to identify the failing hook in the reporter output like this.

Actually I don't like how failing `beforeAll` and `afterAll` hooks are renamed, based on `hook.ctx.currentTest`.
Setting `if (name === HOOK_TYPE_BEFORE_ALL) { hook.ctx.currentTest = hook.parent.tests[0]; } ...` is not really correct. The context should be the suite not the first/last test. But this topic is out of scope and should be checked carefully before changing anything.

**Comment by cspotcode** [comment]
Right, so the current title rewriting is bad and should be changed.  What's
the right approach for teams affected by #4383?

File: test/integration/multiple-done.spec.js [hunk 2]
```diff
@@ -97,7 +97,7 @@ describe('multiple calls to done()', function() {
       expect(res.failures[0], 'to satisfy', {
         fullTitle: 'suite "before all" hook in "suite"',
         err: {
-          message: /done\(\) called multiple times in hook <suite "before all" hook> of file.+multiple-done-before\.fixture\.js/
+          message: /done\(\) called multiple times in hook <suite "before all" hook in "suite"> of file.+multiple-done-before\.fixture\.js/
```
Comment (boneskull) [inline test/integration/multiple-done.spec.js:100]: this doesn't read quite right... `suite "before all" hook in "suite"`

File: test/integration/multiple-done.spec.js [hunk 3]
```diff
@@ -119,20 +119,18 @@ describe('multiple calls to done()', function() {
...
-          fullTitle: 'suite "before each" hook in "suite"',
-          err: {
-            message: /done\(\) called multiple times in hook <suite "before each" hook> of file.+multiple-done-before-each\.fixture\.js/
-          }
+      expect(res.failures[0], 'to equal', res.failures[1]);
+      expect(res.failures[0], 'to satisfy', {
+        fullTitle: 'suite "before each" hook in "suite"',
+        err: {
+          message: /done\(\) called multiple times in hook <suite "before each" hook in "suite"> of file.+multiple-done-before-each\.fixture\.js/,
+          multiple: [
```
Comment (boneskull) [inline test/integration/multiple-done.spec.js:127]: this error object is weird, but I guess that's what it does.

you can combine this into a single assertion:

```js
expect(res.failures[0], 'to equal', res.failures[1])
  .and('to satisfy', {
    // etc.
  });
```

File: lib/runner.js [hunk 4]
```diff
@@ -419,20 +419,6 @@ Runner.prototype.fail = function(test, err, force) {
  * @param {Error} err
  */
 Runner.prototype.failHook = function(hook, err) {
```
Comment (boneskull) [inline lib/runner.js:421]: could probably just remove `failHook` and replace its usage with calls directly to `fail`

File: test/integration/multiple-done.spec.js (hunk 2 above)
Comment (boneskull) [reply test/integration/multiple-done.spec.js:100]: actually, it appears `"suite"` is the _name_ of the suite, which is confusing, so maybe it's not a blocker at all.

File: test/integration/multiple-done.spec.js (hunk 3 above)
Comment (boneskull) [reply test/integration/multiple-done.spec.js:127]: (likewise the assertion(s) in the new test may be able to be combined this way)

File: test/integration/multiple-done.spec.js (hunk 2 above)
Comment (cspotcode) [reply test/integration/multiple-done.spec.js:100]: Yeah, tripped me up, too.

File: test/integration/multiple-done.spec.js (hunk 3 above)
Comment (cspotcode) [reply test/integration/multiple-done.spec.js:127]: Yeah, you probably already know this, but I rewrote the assertion to point out that both items of the array actually refer to the same object.  I can't do a `===` check in the tests, because it's been converted to/from JSON, so the assertions are running against 2 different parsed copies of the same object.  Does `'to equal'` handle that?

This happens because when a single test/hook has multiple failures, the first error is reused, and the `multiple` array is created to store the others.  Ideally I think mocha should be creating a new "hookinvocation" instance for each time the hook runs, where each "hookinvocation" can store a reference to the test case it's paired to.  But I don't think I'll have time for that size of code change.

File: lib/runner.js (hunk 4 above)
Comment (cspotcode) [reply lib/runner.js:421]: Will do.

**Comment by cspotcode** [comment]
@boneskull thanks, I think I addressed all your feedback and tests are passing.
