### PR TITLE
Fix message if no files found

### LINKED ISSUE #3646: too much noise if no files found
To reproduce, run `mocha` (verbatim) in a directory with no `test/` subdir:

```
Warning: cannot find any files matching pattern "test/": 'test/'
✖ No test files found
```

We should remove the warning and use the error.  Print the dir it's looking for, but only once.  :smile:

I think @craigtaub might be good to address this since he changed some errors recently, but please unassign/re-label if you don't want to do it.

### PR DESCRIPTION
**Pull request by craigtaub**
### Description of the Change

Previously would print a warning for each missing file/dir, then an error if no valid files were found.
Now prints slimmer warnings and errors only if no tests found.
Tests cover both scenarios.

### Alternate approach

Print an error for each missing file/dir (and no final error). Still exit if no valid files were found.
Nasty as flags everything as an error even if there is a passing test

### Nothing given
Command: `mocha`
New output:
```
Error: Cannot find any files matching pattern "test/"
```
Previous output:
```
Warning: cannot find any files matching pattern "test/": 'test/'
✖ No test files found
```

Difference = No warning and slimmer message

### Nothing found
Command: `mocha -R json-stream --no-config "test/integration/fixtures/glob/**/*-none.js"`
New output:
```
Error: Cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none.js"
```
Previous output:
```
Warning: cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none.js": 'test/integration/fixtures/glob/**/*-none.js'
✖ No test files found
```

Difference = No warning and slimmer message

### 1 found but 1 not found:
Command: `mocha -R json-stream --no-config "test/integration/fixtures/glob/**/*.js" "test/integration/fixtures/glob/**/*-none.js"`
New output:
```
Warning: Cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none.js"
["start",{"total":2}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["end",{"suites":2,"tests":2,"passes":2,"pending":0,"failures":0,"start":"2019-01-03T19:03:34.591Z","end":"2019-01-03T19:03:34.593Z","duration":2}]
```
Previous output:
```
Warning: cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none.js": 'test/integration/fixtures/glob/**/*-none.js'
["start",{"total":2}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["end",{"suites":2,"tests":2,"passes":2,"pending":0,"failures":0,"start":"2019-01-03T17:53:56.843Z","end":"2019-01-03T17:53:56.845Z","duration":2}]
```

Difference = slimmer warning

### 1 found but 2 not found:
Command: `mocha -R json-stream --no-config "test/integration/fixtures/glob/**/*.js" "test/integration/fixtures/glob/**/*-none.js" "test/integration/fixtures/glob/**/*-none-again.js"`
New output:
```
Warning: Cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none.js"
Warning: Cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none-again.js"
["start",{"total":2}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["end",{"suites":2,"tests":2,"passes":2,"pending":0,"failures":0,"start":"2019-01-03T19:03:55.208Z","end":"2019-01-03T19:03:55.210Z","duration":2}]
```
Previous output:
```
Warning: cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none.js": 'test/integration/fixtures/glob/**/*-none.js'
Warning: cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none-again.js": 'test/integration/fixtures/glob/**/*-none-again.js'
["start",{"total":2}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["end",{"suites":2,"tests":2,"passes":2,"pending":0,"failures":0,"start":"2019-01-03T17:54:34.393Z","end":"2019-01-03T17:54:34.395Z","duration":2}]
```

Difference = Simmer warnings

### 2 not found:
Command: `mocha -R json-stream --no-config "test/integration/fixtures/glob/**/*-none.js" "test/integration/fixtures/glob/**/*-none-again.js"`
New output:
```
Error: Cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none.js"
Error: Cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none-again.js"
```
Previous output:
```
Warning: cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none.js": 'test/integration/fixtures/glob/**/*-none.js'
Warning: cannot find any files matching pattern "test/integration/fixtures/glob/**/*-none-again.js": 'test/integration/fixtures/glob/**/*-none-again.js'
✖ No test files found
```

Difference = Warnings swapped for errors and no extra error.

### 1 found:
Command: `mocha -R json-stream --no-config "test/integration/fixtures/glob/**/*.js"`
New output:
```
["start",{"total":2}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["end",{"suites":2,"tests":2,"passes":2,"pending":0,"failures":0,"start":"2019-01-03T17:01:17.934Z","end":"2019-01-03T17:01:17.938Z","duration":4}]
```
Previous output:
```
["start",{"total":2}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["pass",{"title":"should find this test","fullTitle":"globbing test should find this test","duration":0,"currentRetry":0}]
["end",{"suites":2,"tests":2,"passes":2,"pending":0,"failures":0,"start":"2019-01-03T17:55:06.996Z","end":"2019-01-03T17:55:06.999Z","duration":3}]
```
Difference = nothing

### Applicable issues
Fixes #3646
(semver-patch)

### CODE REVIEW

File: lib/cli/run-helpers.js [hunk 1]
```diff
@@ -138,13 +138,14 @@ exports.handleFiles = ({
   spec = []
 } = {}) => {
   let files = [];
+  let errors = [];
```
Comment (boneskull) [inline lib/cli/run-helpers.js]: can this be `const`?

File: lib/cli/run-helpers.js [hunk 2]
```diff
@@ -164,8 +165,16 @@ exports.handleFiles = ({
...
-    console.error(ansi.red(`${symbols.error} No test files found`));
+    // print messages as an error
+    errors.forEach(message => {
+      console.error(ansi.red(`${symbols.error} ${message}`));
+    });
     process.exit(1);
+  } else {
+    // print messages as an warning
+    errors.forEach(message => {
+      console.warn(`Warning: ${message}`);
```
Comment (boneskull) [inline lib/cli/run-helpers.js]: use `ansi.yellow` 😉

File: test/integration/glob.spec.js [hunk 3]
```diff
@@ -28,7 +28,7 @@ describe('globbing', function() {
           expect(
             results.stderr,
             'to contain',
-            'cannot find any files matching pattern "./*-none.js"'
+            '✖ Cannot find any files matching pattern "./*-none.js"'
```
Comment (boneskull) [inline test/integration/glob.spec.js]: can you pull in the symbol from `log-symbols`? this may fail on windows

File: lib/cli/run-helpers.js [hunk 4]
```diff
@@ -164,8 +165,16 @@ exports.handleFiles = ({
   });
 
   if (!files.length) {
-    console.error(ansi.red(`${symbols.error} No test files found`));
+    // print messages as an error
+    errors.forEach(message => {
+      console.error(ansi.red(`${symbols.error} ${message}`));
```
[the remark this answers is not in the document]
Comment (craigtaub) [reply lib/cli/run-helpers.js]: Do you mean why use "X" symbol over "Error"? Im not sure, you can see it was used before.

File: test/integration/glob.spec.js (hunk 3 above)
Comment (plroebuck) [reply test/integration/glob.spec.js]: Or just leave it and the pattern out...
```js
             'Cannot find any files matching pattern'
```

File: test/integration/glob.spec.js [hunk 5]
```diff
@@ -77,7 +77,7 @@ describe('globbing', function() {
           expect(
             results.stderr,
             'to contain',
-            'cannot find any files matching pattern'
+            '✖ Cannot find any files matching pattern "./*-none.js"'
```
Comment (plroebuck) [inline test/integration/glob.spec.js]: same

File: test/integration/glob.spec.js [hunk 6]
```diff
@@ -125,7 +125,7 @@ describe('globbing', function() {
             expect(
               results.stderr,
               'to contain',
-              'cannot find any files matching pattern'
+              '✖ Cannot find any files matching pattern "./**/*-none.js"'
```
Comment (plroebuck) [inline test/integration/glob.spec.js]: same

File: lib/cli/run-helpers.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (plroebuck) [reply lib/cli/run-helpers.js]: https://github.com/mochajs/mocha/blob/5bd33a0ba201d227159759e8ced86756595b0c54/bin/_mocha#L556

File: test/integration/glob.spec.js (hunk 3 above)
Comment (craigtaub) [reply test/integration/glob.spec.js]: Good idea.

File: lib/cli/run-helpers.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (boneskull) [reply lib/cli/run-helpers.js]: *shrug* I would prefer to keep the symbol; do whatever you wish

File: test/integration/glob.spec.js (hunk 3 above)
Comment (craigtaub) [reply test/integration/glob.spec.js]: Hmm I actually think listing the errors is better, from the users perspective it's more helpful and easier to see the mistake that way. I've used it myself during his pr.

File: lib/cli/run-helpers.js [hunk 7]
```diff
@@ -164,8 +164,16 @@ exports.handleFiles = ({
   });
 
   if (!files.length) {
-    console.error(ansi.red(`${symbols.error} No test files found`));
+    // print messages as an error
+    errors.forEach(message => {
+      console.error(ansi.red(`Error: ${message}`));
+    });
```
Comment (plroebuck) [inline lib/cli/run-helpers.js]: This should have simply said:
```js
    console.error(ansi.red('Error: No test files found'));
```
Nothing is gained by saying more and now we have **both** warnings and errors with the same message.

File: test/integration/glob.spec.js [hunk 8]
```diff
@@ -28,7 +28,7 @@ describe('globbing', function() {
           expect(
             results.stderr,
             'to contain',
-            'cannot find any files matching pattern "./*-none.js"'
+            'Error: Cannot find any files matching pattern "./*-none.js"'
```
Comment (plroebuck) [inline test/integration/glob.spec.js]: test pattern (filename) should not be part of check for maintainability.

File: test/integration/glob.spec.js [hunk 9]
```diff
@@ -77,7 +77,7 @@ describe('globbing', function() {
           expect(
             results.stderr,
             'to contain',
-            'cannot find any files matching pattern'
+            'Error: Cannot find any files matching pattern "./*-none.js"'
```
Comment (plroebuck) [inline test/integration/glob.spec.js]: test pattern (filename) should not be part of check for maintainability.

File: test/integration/glob.spec.js [hunk 10]
```diff
@@ -125,7 +125,7 @@ describe('globbing', function() {
             expect(
               results.stderr,
               'to contain',
-              'cannot find any files matching pattern'
+              'Error: Cannot find any files matching pattern "./**/*-none.js"'
```
Comment (plroebuck) [inline test/integration/glob.spec.js]: test pattern (filename) should not be part of check for maintainability.

File: lib/cli/run-helpers.js (hunk 7 above)
Comment (craigtaub) [reply lib/cli/run-helpers.js]: They don't show at the same time though. I mentioned in my comment earlier I felt giving full error details was helpful, in that I found it useful myself.

File: lib/cli/run-helpers.js [hunk 11]
```diff
@@ -138,13 +137,14 @@ exports.handleFiles = ({
   spec = []
 } = {}) => {
   let files = [];
+  const errors = [];
```
Comment (plroebuck) [inline lib/cli/run-helpers.js]: More specific about what you're storing.
```js
  const messages = [];
```

File: test/integration/glob.spec.js (hunk 3 above)
Comment (plroebuck) [reply test/integration/glob.spec.js]: So if user gives 20 globs and _none_ exist, one message per is somehow more informative than just saying "none found"? I disagree. 
For warnings, fine -- but not when _none_ exist.

Comment (boneskull) [reply test/integration/glob.spec.js]: As @craigtaub stated, it was useful information, so if some *subset* of the paths are not found, it seems reasonable to list them (but not if *all* of them are not found).

FWIW, a user can avoid this problem altogether by using shell expansion, but that's not portable.

File: lib/cli/run-helpers.js (hunk 7 above)
Comment (boneskull) [reply lib/cli/run-helpers.js]: I'm a bit confused about when we are going to show errors vs warnings...

Comment (plroebuck) [reply lib/cli/run-helpers.js]: Wasn't the name of the issue "too much noise if no files found"?

Comment (boneskull) [reply lib/cli/run-helpers.js]: I just didn't want to see a warning about it (which duplicated the filenames) and then *another* error.  If that's fixed, then great

File: test/integration/glob.spec.js (hunk 3 above)
Comment (plroebuck) [reply test/integration/glob.spec.js]: If a subset don't exist, those would be warnings -- stated I had no problem with that.
Just the "none found" error case.

File: lib/cli/run-helpers.js (hunk 7 above)
Comment (craigtaub) [reply lib/cli/run-helpers.js]: Check the description I tried to give full details on what shows when

File: test/integration/glob.spec.js (hunk 3 above)
Comment (craigtaub) [reply test/integration/glob.spec.js]: Ok i think its clear you both feel the single error message is better than multiple error messages. For debugging purposes I found the multiple one better, the initial idea of using an error was to indicate nothing did run, but perhaps its not clear enough.

File: test/integration/glob.spec.js (hunk 8 above)
Comment (craigtaub) [reply test/integration/glob.spec.js]: Wasn't if on purpose, I thought there was nothing outstanding so I merged it. 
Have made a new PR continuing the work.
