### PR TITLE
fix: test link in html reporter

### LINKED ISSUE #5102: 🐛 Bug: test links in the browser reporter keep the original fgrep and invert params
### Bug Report Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [x] I want to provide a PR to resolve this

### Expected

A link of the browser reporter should remove `fgrep` and `invert` parameters in the original URL.

### Actual

A link of the browser reporter keeps the original `fgrep` and `invert` parameters in the original URL.

### Minimal, Reproducible Example

1. Create a test page like:

```html
<!DOCTYPE html>
<meta charset="UTF-8">
<link rel="stylesheet" href="mocha.css">
<div id="mocha"></div>
<script src="mocha.js"></script>
<script>
mocha.setup('bdd');

describe('tests', function () {
  it('test1', function () {});
  it('test2', function () {});
});

mocha.run();
</script>
```

2. Open the page in the browser.

3. Append `?fgrep=tests` in the address and visit it.

4. Wait for the test to complete, and click the replay link of `test1`.

### Versions

mocha@10.3.0 in javascript ES2018

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by danny0838**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5102
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Fix as mentioned in the [related issue comment](https://github.com/mochajs/mocha/issues/5102#issuecomment-1966919750).

### CODE REVIEW

File: lib/reporters/html.js [hunk 1]
```diff
@@ -260,9 +260,9 @@ function HTML(runner, options) {
 function makeUrl(s) {
   var search = window.location.search;
 
-  // Remove previous grep query parameter if present
+  // Remove previous {grep, fgrep, invert} query parameters if present
   if (search) {
-    search = search.replace(/[?&]grep=[^&\s]*/g, '').replace(/^&/, '?');
+    search = search.replace(/[?&](?:f?grep|invert)=[^&\s]*/g, '').replace(/^&/, '?')
```
Comment (JoshuaKGoldberg) [inline lib/reporters/html.js:265]: [Style] Nit: everything else uses `;`, unrelated change ~

```suggestion
    search = search.replace(/[?&](?:f?grep|invert)=[^&\s]*/g, '').replace(/^&/, '?');
```

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks! Just one style nit, but nothing functionally blocking. 🚀 

Will leave open for a bit in case anybody from @mochajs/maintenance-crew wants to take a look.

**Comment by JoshuaKGoldberg** [comment]
Oh, and - please sign the CLA so we can accept this @danny0838.

**Review by JoshuaKGoldberg — APPROVED** [review]
