### PR TITLE
Revert 00ca06b; closes #3414

### LINKED ISSUE #3414: --bail and --retries events: multiple "end" occurs
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

I found out that when both `--retries` and `--bail` option are used "end" event is emitted 2+ times. While this works fine for reporters I'm not sure if this behaviour is okay. However, this is even trickier when there's no `--exit` option specified. What is the test supposed to do after the bailed "end"?

### Steps to Reproduce

CLI: `mocha -R test/util/events-reporter.js --bail --retries 1 test/bail-and-retries/index.spec.js`

```javascript
// test/util/events-reporter.js
const Base = require('mocha').reporters.Base;

module.exports = class Reporter extends Base {
    constructor(runner) {
        super(runner);

        [
            'waiting',
            'start',
            'end',
            'suite',
            'suite end',
            'test',
            'test end',
            'pass',
            'fail',
            'pending',
            'hook',
            'hook end',
        ].forEach((evtName) => {
            runner.on(evtName, this.onRunnerEventFired.bind(this, evtName));
        });
    }

    onRunnerEventFired(evtName) {
        console.log(evtName);
    }
};

// test/bail-and-retries/index.spec.js
describe('suite', () => {
    it('case', () => {
        throw new Error('fail');
    });
});
```

**Expected behavior:** needs discussion. Probably depends on `--exit`: if it's specified the program should stop executing after the bailed "end" is emitted. If it's not: 🤷‍♂️ 

**Actual behavior:** bailed "end" is emitted, then all other events occur including second "end"

**Reproduces how often:** 100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.2.0
- The output of `node --version`: 8.11.2
- The version and architecture of your operating system: OSX
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash

### PR DESCRIPTION
**Pull request by boneskull**
- Reverts 00ca06b
- Update event-order tests
- Added retries-and-bail case

Reopens #2753

### CODE REVIEW

**Comment by boneskull** [comment]
cc @1999

File: test/integration/helpers.js [hunk 1]
```diff
@@ -81,27 +81,30 @@ module.exports = {
...
-                'Failed to parse JSON reporter output.\nArgs: %O\nResult:\n\n%O',
-                args,
+                'Failed to parse JSON reporter output: %s\n\nResult:%O',
+                err,
                 res
               )
             )
           );
         }
+        fn(null, result);
```
Comment (plroebuck) [inline test/integration/helpers.js]: Why move this? Original location was more to the point.
```js
try {
  return fn(null, toJSONRunResult(res));
} catch (err) {
  return fn(
    new Error(
      format(
        'Failed to parse JSON reporter output: %s\n\nResult:%O',
        err,
        res
      )
    )
  );
}
```

File: test/integration/options/grep.spec.js [hunk 2]
```diff
@@ -28,8 +21,7 @@ describe('--grep', function() {
 
   describe('should run specs matching a RegExp', function() {
     it('with RegExp-like strings (pattern follow by flag)', function(done) {
```
Comment (plroebuck) [inline test/integration/options/grep.spec.js]: ...followed...

File: test/integration/options/grep.spec.js [hunk 3]
```diff
@@ -68,40 +58,45 @@ describe('--grep', function() {
...
+        ['--fgrep', 'first', '--grep', 'second'],
         function(err, res) {
           if (err) {
             return done(err);
           }
-          expect(res, 'to satisfy', {
-            code: 1,
-            output: /--invert.*--grep <regexp>/
-          });
+          expect(res, 'to have failed with output', /mutually exclusive/i);
```
Comment (plroebuck) [inline test/integration/options/grep.spec.js]: no longer verifies failure exit code

File: test/integration/options/grep.spec.js [hunk 4]
```diff
@@ -68,40 +58,45 @@ describe('--grep', function() {
...
+        function(err, res) {
+          if (err) {
+            return done(err);
+          }
+          expect(
+            res,
+            'to have failed with output',
+            /--invert.*--grep <regexp>/
+          );
+          done();
```
Comment (plroebuck) [inline test/integration/options/grep.spec.js]: no longer verifies failure exit code

File: test/integration/options/compilers.spec.js [hunk 5]
```diff
@@ -4,20 +4,18 @@ var helpers = require('../helpers');
...
-  it('should fail', function(done) {
-    invokeMocha(args, function(err, res) {
-      if (err) {
-        return done(err);
-      }
-
-      expect(res.code, 'to be', 1);
-      done();
-    });
+        expect(res, 'to have failed with output', /compilers is deprecated/i);
```
Comment (plroebuck) [inline test/integration/options/compilers.spec.js]: no longer verifies failure exit code

File: test/integration/options/grep.spec.js [hunk 6]
```diff
@@ -68,40 +58,45 @@ describe('--grep', function() {
...
-      args = ['--fgrep', 'first', '--grep', 'second'];
-
-      runMocha(fixture, args, function(err, res) {
-        if (err) {
-          return done(err);
-        }
-        expect(res, 'to have failed');
-        done();
-      });
+describe('--invert', function() {
```
Comment (plroebuck) [inline test/integration/options/grep.spec.js]: this breaks lexical ordering...

File: test/integration/options/compilers.spec.js (hunk 5 above)
Comment (boneskull) [reply test/integration/options/compilers.spec.js]: it does, actually: 'to have failed with output' ensures the exit code is nonzero

File: test/integration/helpers.js (hunk 1 above)
Comment (boneskull) [reply test/integration/helpers.js]: because the logic was incorrect.  it would catch a potential error thrown out of the `fn` callback.

Comment (boneskull) [reply test/integration/helpers.js]: I'll add a comment explaining myself

File: test/integration/options/grep.spec.js (hunk 6 above)
Comment (boneskull) [reply test/integration/options/grep.spec.js]: again, if we can't automate the check or reformat automatically...

[eslint-import-order-alphabetical](https://www.npmjs.com/package/eslint-plugin-import-order-alphabetical) is probably a good place to start implementing such a thing.  it might not have a `--fix` implementation, but the check is better than nothing.

File: test/assertions.js [hunk 7]
```diff
@@ -100,6 +100,24 @@ exports.mixinMochaAssertions = function(expect) {
         code: expect.it('to be greater than', 0)
       });
     })
+    .addAssertion(
```
Comment (boneskull) [inline test/assertions.js]: @plroebuck new assertions for common "fail and validate output" checks

File: test/assertions.js [hunk 8]
```diff
@@ -100,6 +100,24 @@ exports.mixinMochaAssertions = function(expect) {
...
+      '<RawRunResult|RawResult> [not] to have failed (with|having) output <any>',
+      function(expect, result, output) {
+        expect(result, '[not] to satisfy', {
+          code: expect.it('to be greater than', 0),
+          output: output
+        });
```
Comment (plroebuck) [inline test/assertions.js]: OK. See your rule, but don't see how it would be satisfied.
```js
// simulate output from [_spawnMochaWithListeners](https://github.com/mochajs/mocha/blob/c77d396e7607289a40c2cf5713403a2ed72c9bf9/test/integration/helpers.js#L261)
var res = {
  output: ['{ "foo": 123, "bar": true, "baz": "abc" }'],
  code: 1,
  args: '--whatever'
};
// convert run result from [toJSONRunResult](https://github.com/mochajs/mocha/blob/c77d396e7607289a40c2cf5713403a2ed72c9bf9/test/integration/helpers.js#L186)
var result = toJSONRunResult(res);
// => { foo: 123, bar: true, baz: 'abc', code: 1 }
// fn(null, result);

It still has `code`, but wasn't `output` lost in translation?
```

File: test/integration/options/grep.spec.js (hunk 6 above)
Comment (plroebuck) [reply test/integration/options/grep.spec.js]: The ordering was done by filename, each option in its own file with a single `describe`, merged just two weeks ago...

File: test/assertions.js (hunk 8 above)
Comment (boneskull) [reply test/assertions.js]: hmm, I still don't really follow.  this does not apply to `JSONRunResult`; it can't be used with `runMochaJSON`.  generally when we use `runMochaJSON` we're more interested in specific information, e.g., did test _x_ pass and how many pending tests were there.

File: test/integration/options/grep.spec.js (hunk 6 above)
Comment (boneskull) [reply test/integration/options/grep.spec.js]: I'll move `--invert` into its own file for consistency.  my reasoning was that a) the test was already in this file and b) the option can't be used without (f)grep

Comment (plroebuck) [reply test/integration/options/grep.spec.js]: > my reasoning was that a) the test was already in this file and b) the option can't be used without (f)grep

That's why it was previously nested...

File: test/assertions.js (hunk 8 above)
Comment (plroebuck) [reply test/assertions.js]: I see now. Assumed this was related to your change in "test/integration/helpers.js", but it's unrelated to the other unrelated changes of reverting the original PR...
