### PR TITLE
fix: surface ts-node compile errors

### LINKED ISSUE #5555: 🐛 Bug: "Cannot find module" if module contains ts-node style 'TSError'
### Bug Report Checklist

- [x] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/main/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md)
- [x] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [x] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [ ] I want to provide a PR to resolve this

### Expected

When i have TS error in a module included in a test, it should show the TS error

### Actual

When there is a TS error it shows "Cannot find module".

### Minimal, Reproducible Example

I have what i think is a pretty simple typescript setup but at some point the compilation error handling has started causing a very hard to debug "Cannot find module", error rather than the TS error.

This is a stripped down repo which still exhibits the issue:
https://github.com/sam-super/mocha-ts-node-bug

### Versions

mocha@11.7.5
node@v24.11.0

### Additional Info

E.g. from the reference example repo:

```
npm run test -- test/included-module-ts-error.test.ts

Exception during run: Error: Cannot find module '[...]/test/helpers/bad-module' imported from [...]/test/included-module-ts-error.test.ts
```

Possibly related issue is it manages to execute a test with a TS error in the top-level test file/suite without complaint:
```
npm run test -- test/top-level-compilation.test.ts

  should error with ts error
    ✔ but passes when it should have failed
```

### PR DESCRIPTION
**Pull request by sam-super**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5555
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Prevents "Cannot find module" when there are TS errors by prevent fallback to 'import()' when it errors.

The downside is this is tightly coupled to how ts-node throws errors when loading modules. However, this change seems unlikely to have any unexpected side-effects, so the risk is that it wont help if someone is using a different TS loader, but it's still a net gain for most.

### CODE REVIEW

File: lib/nodejs/esm-utils.js [hunk 1]
```diff
@@ -97,6 +97,9 @@ const requireModule = async (file, esmDecorator) => {
   try {
     return require(file);
   } catch (requireErr) {
+    if (requireErr.name === 'TSError') {
```
Comment (JoshuaKGoldberg) [inline lib/nodejs/esm-utils.js:101]: [Refactor] Hmm. _Hmm_. Hardcoding `'TSError'` for `ts-node` only solves for `ts-node`. Ideally I don't think we should hardcode specific userland names into the general Mocha library. But I'm not sure there's a way to do that...

To recap, the root cause as I understand it is that the logic right now results in the wrong error getting shown to users:

1. First, `requireModule` attempts to `require(file)`
2. If that fails, it attempts to `formattedImport(file)`
3. If that also fails, the error from `formattedImport` is shown

...but in this case, it's really the error from `require` that I think we'd want.

This is similar to the previous #5235 -> #5393 -> #5408 -> #5498.

Anyway, for this new entry in the saga, I really don't see a better way of doing things. `ts-node` is the only popular userland library I know of that type-checks code as part of imports. That practice as a whole has been out of favor for a while - both as a _"this is slow, do it separately"_ concern and especially now that Node.js supports `.ts` files natively. So I don't think we'll see new libraries with new names to add.

@mark-wiemer I _think_ this change is reasonable, but I want to get your thoughts on it too. Is there some nice strategy I'm missing?

File: lib/nodejs/esm-utils.js [hunk 2]
```diff
@@ -97,6 +97,9 @@ const requireModule = async (file, esmDecorator) => {
...
+      throw requireErr;
+    }
     debug("requireModule caught err: %O", requireErr.message);
```
Comment (JoshuaKGoldberg) [inline lib/nodejs/esm-utils.js]: [Bug] Let's move the new code to after this `debug()` line. `DEBUG=* npm run test` is a nice helpful thing users do.

File: test/node-unit/esm-utils.spec.js
Comment (JoshuaKGoldberg) [inline test/node-unit/esm-utils.spec.js:1]: [Praise] Very clean new test. Nice 🙂

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
I agree with the strategy, but would really like a spot check from another maintainer to make sure there's no way we can get around it.

Just requesting changes on moving the `debug()` line.

Thanks!

File: lib/nodejs/esm-utils.js (hunk 2 above)
Comment (sam-super) [reply lib/nodejs/esm-utils.js]: will do!

File: lib/nodejs/esm-utils.js (hunk 1 above)
Comment (sam-super) [reply lib/nodejs/esm-utils.js:101]: I agree it's not perfect.

To add something else to the mix i also sent this bug:
https://github.com/mochajs/mocha/issues/5579
The PR i will put up for that will be similar to this PR and will add another condition like so:
image

With a growing list of exceptions, it could point to a the default behavior (of a require error falling back to an import ) being the wrong way round. I wondered if it should only fall back in specific scenarios based on the error (inverting the default so it doesn't fall back), but i appreciate that might be an even worse case of whack-a-mole.

File: lib/nodejs/esm-utils.js (hunk 2 above)
Comment (sam-super) [reply lib/nodejs/esm-utils.js]: done: 4a25ae7

File: lib/nodejs/esm-utils.js (hunk 1 above)
Comment (mark-wiemer) [reply lib/nodejs/esm-utils.js:101]: I think the current PR is reasonable here. Swapping default behavior is more likely to cause more harm than good, we don't have a comprehensive test suite on which errors should go in which buckets, so let's not rock the boat too much.

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks! 🙌

**Review by mark-wiemer — APPROVED** [review]

**Comment by mark-wiemer** [comment]
Test failure is known transient issue (#5361), merging. Thank you!

**Comment by SchroederSteffen** [comment]
Thanks for the fix. Could this be downported to v11?

**Comment by mark-wiemer** [comment]
Created https://github.com/mochajs/mocha/issues/6029 :)
