### PR TITLE
Fix #2083: HTML reporter regression causing duplicate error output

### LINKED ISSUE #2083: Regression: Failures rendering twice
I just happened to start up a simple hello world mocha test project (to test something else :) ), and I noticed that versions >= 2.4 now double-render the failure in my example.  Reverting to 2.3.3 makes the behavior go away.  I will try to get to the bottom of it, but I see several releases in the last few days so I thought maybe you'd want to know.

https://github.com/ahamid/mocha-phantomjs-blanket/tree/mocha-failure-double-render

double-render-failure

### PR DESCRIPTION
**Pull request by danielstjules**
Fixed #2083

This is a minor refactor of the HTML reporter to listen to `pass/fail/pending` events rather than `test end`, just like the spec/dot reporters.

--------
As seen below, the sync error is displayed only a single time:

--------

screen shot 2016-02-16 at 12 16 50 am

--------

And the async errors are each correctly displayed. This is the behavior https://github.com/mochajs/mocha/pull/1981 was intended to fix. Prior to that PR, none of the errors below were displayed in the HTML reporter.

--------

screen shot 2016-02-16 at 12 16 57 am

### CODE REVIEW

**Comment by danielstjules** [comment]
cc @boneskull

**Comment by danielstjules** [comment]
This is compatible with https://github.com/mochajs/mocha/pull/2081 since the `pending` event now fires after checking `isPending()`

**Comment by boneskull** [comment]
@danielstjules cool.  do you have any recommendations for how to test this?

**Comment by boneskull** [comment]
#2079 is still a thing.

**Comment by boneskull** [comment]
I *really* don't want to release anything without #2079 being addressed in some fashion

**Comment by danielstjules** [comment]
Aside from manual testing? If you open test/browser/index.html in master, you'll see that normal errors are duplicated, but async errors after a test completed are correctly shown:

screen shot 2016-02-17 at 9 26 24 am

screen shot 2016-02-17 at 9 26 36 am

Comparing that against the build of this PR/branch, async errors post-test completion are still shown, and normal errors are only rendered once.

**Comment by danielstjules** [comment]
In regards to the async errors, this is the same expected behavior seen from the node reporters:

``` javascript
$ cat example.js
it('test', function(done) {
  setTimeout(done, 10);
  setTimeout(done, 20);
});

it('test2', function(done) {
  setTimeout(done, 30);
});

$ ./bin/mocha example.js


  ․․․

  2 passing (51ms)
  1 failing

  1)  test:
     Error: done() called multiple times
      at Test.Runnable (lib/runnable.js:54:17)
      at new Test (lib/test.js:22:12)
      at context.it.context.specify (lib/interfaces/bdd.js:85:18)
      at Object.<anonymous> (example.js:1:63)
      at Array.forEach (native)
      at Object.<anonymous> (bin/_mocha:403:18)
      at node.js:868:3
```

**Comment by danielstjules** [comment]
> I really don't want to release anything without #2079 being addressed in some fashion

I can work on that tonight. But I don't think I'll have an exhaustive enough automated browser test suite ready to reveal issues beyond manually running those HTML files in IE8/Safari/Chrome.

**Comment by boneskull** [comment]
at minimum then I'd want someone to test IE8, phantomjs 1.x and phantomjs 2.x manually.  specifically, see if mochify breaks.

**Comment by jnbt** [comment]
Any updates on this? I think the HTML reports are still broken...

**Comment by justinfagnani** [comment]
Also curious about this PR, the bug is messing with reporting downstream of mocha. Are all PRs on hold until #2079 is resolved?

**Comment by dasilvacontin** [comment]
@justindujardin pretty much, sorry for the hassle.

**Comment by justinfagnani** [comment]
Honestly, this makes me question our dependence on Mocha. This fix is 2 months old.

**Comment by boneskull** [comment]
@justinfagnani Hi!  Instead of complaining, feel free to help with #2079.

**Comment by ScottFreeCode** [comment]
I've been experimenting with a set of tests to check for problems like this. It isn't pretty, I don't know if it will work in any kind of automatic testing such as discussed in #2112, and the CLI won't work unless I can get the same HTML report as the browser uses; but at least the set of test cases should be a good starting point (although you may have to go through and tweak which situations are intended to be reported as how many passes and failures, I'm not 100% sure I got it right). It's also not really unit-testing the matter -- if there's the wrong number of results there's no indication as to whether it's a flaw in the test runner or the reporter, if there's the right number of results that doesn't mean the responsibilities involved in getting them are correctly divided between the test runner and the reporter -- but it's better than nothing, I figure (I guess if we wanted to unit test Mocha's internals we'd have to use the non-bundled scripts... and to make it run in the browser would probably end up basically creating a second bundle containing the internal unit tests?...).

I've put what I've got so far up in a gist here: https://gist.github.com/ScottFreeCode/f8b0864781414f96594f67b77ddee469

**Comment by maciejjankowski** [comment]
I wonder why is this stalled...
shouldn't you add `PR Please` label?

**Comment by pluma** [comment]
I can see why you would want to fix #2079 first but this change is trivial compared to the rabbit hole that is automated browser testing. I believe greenlighting this fix despite the freeze would help a lot of people. As it is, this bug is making browser reports significantly less useful, so the question of browser support doesn't really come into it.

**Comment by boneskull** [comment]
I'm going to rebase this onto `master` and see what happens.

File: lib/reporters/html.js [hunk 1]
```diff
@@ -128,88 +128,82 @@ function HTML(runner) {
...
+  function appendToStack(el) {
     // Don't call .appendChild if #mocha-report was already .shift()'ed off the stack.
     if (stack[0]) {
       stack[0].appendChild(el);
     }
-  });
+  }
+
+  function updateStats() {
+    // TODO: add to stats
```
Comment (boneskull) [inline lib/reporters/html.js]: @danielstjules does this TODO mean this PR isn't ready?

**Comment by boneskull** [comment]
In general, I think this looks good. Just want some feedback from @danielstjules to ensure it's ready to merge.

File: lib/reporters/html.js [hunk 2]
```diff
@@ -128,88 +128,82 @@ function HTML(runner) {
...
-      progress.update(percent).draw(ctx);
+  runner.on('fail', function(test) {
+    var el = fragment('<li class="test fail"><h2>%e <a href="%e" class="replay">‣</a></h2></li>',
+      test.title, self.testURL(test));
+    var stackString; // Note: Includes leading newline
+    var message = test.err.toString();
+
+    // <=IE7 stringifies to [Object Error]. Since it can be overloaded, we
+    // check for the result of the stringifying.
+    if (message === '[object Error]') {
```
Comment (dasilvacontin) [inline lib/reporters/html.js]: In the comment you mention `[Object Error]`, but in the code it uses a different casing.

Comment (pluma) [inline lib/reporters/html.js]: @dasilvacontin the code is correct, the comment is wrong.

Comment (dasilvacontin) [inline lib/reporters/html.js]: Thanks for clearing it up @pluma!

**Comment by dasilvacontin** [comment]
LGTM. Sync error is only reported once now. Waiting for the reply about the `TODO`, will release in a day or two if no response is given.

**Comment by dasilvacontin** [comment]
btw: sorry for the wait internet people.

File: lib/reporters/html.js (hunk 2 above)
Comment (danielstjules) [inline lib/reporters/html.js]: If you look further down, I didn't write the comment, just moved around the code :)

File: lib/reporters/html.js (hunk 1 above)
Comment (danielstjules) [inline lib/reporters/html.js]: The comment already existed above https://github.com/mochajs/mocha/pull/2112/files#diff-998e3fb668a2094eedccab3e56199e4fL141

**Comment by danielstjules** [comment]
The diff is unfortunately long for what was a minor refactor. A lot of the code was moved around rather than modified.

File: lib/reporters/html.js (hunk 2 above)
Comment (dasilvacontin) [inline lib/reporters/html.js]: @danielstjules true :)

File: lib/reporters/html.js (hunk 1 above)
Comment (dasilvacontin) [inline lib/reporters/html.js]: @danielstjules true again

**Comment by dasilvacontin** [comment]
Thanks for the fix @danielstjules :). I released it already.
