### PR TITLE
Fix hook pattern of this.skip() in beforeEach hooks

### LINKED ISSUE #2546: Test case skip()ed, beforeEach() hook still executed, afterEach() missed
This with Mocha 3.1.2. Source test file:

``` javascript
"use strict";
describe('outer', function() {

  beforeEach(function() {
    console.log("A");
    this.skip();
  });

  describe('inner', function() {
    beforeEach(function() {
      console.log("B");
    });

    it('test case', function() {
      console.log("C");
    });

    afterEach(function() {
      console.log("Y");
    });
  });

  afterEach(function() {
    console.log("Z");
  });
});
```

Expected output: either "B" **and** "Y" should be printed, or neither "B" **nor** "Y" should be printed.

Actual output: "B" is printed, but not "Y":

```
  outer
    inner
A
B
      - test case


  0 passing (11ms)
  1 pending
```

In general,

* If I call `skip()`, then I would not expect that inner `beforeEach` blocks would be executed.
* If a `beforeEach` block is executed, then the corresponding `afterEach` blocks should also be executed, for symmetry.

### PR DESCRIPTION
**Pull request by juergba**
### Description

#3745 is required for this PR.

The current hook pattern is incorrect. Skipping a test within a `beforeEach` hook executes all inner `beforeEach` hooks, but skips `afterEach` hooks completely.

Some of the `afterEach`  hooks should run to ensure a correct cleanup. This same pattern has already been implemented with failing hooks and also while using the `--bail` option.

The correct hook pattern should be:
- `beforeEach` runs for each test individually and determines at runtime wether to skip or not.
(The failing hook pattern is different: the first hook failure skips all linked tests.)
- since `this.skip()` aborts hook execution, subsequent inner `beforeEach` should be skipped ("B").
- skipped `beforeEach` => skip corresponding `afterEach` hooks as well ("Y").
- `afterEach` hooks of the same/higher suite level than the skipping one should run ("Z").

```js
describe('outer', function() {
  beforeEach(function() {
    console.log("A");              // yes, does run
    this.skip();
  });
  describe('inner', function() {
    beforeEach(function() {
      console.log("B");            // yes, does run  => should not run
    });
    it('test case', function() {
      console.log("C");            // pending
    });
    afterEach(function() {
      console.log("Y");            // no, does not run
    });
  });
  afterEach(function() {
    console.log("Z");              // no, does not run  => should run
  });
});
```

### Description of the Change

We abort `hookDown()` at skipping `suite` level in order to skip subsequent inner `beforeEach` hooks. The same skipping `suite` level is used as entry point for `hookUp()` to skip corresponding inner `afterEach` hooks.

### Applicable issues

closes #2546
closes #2623 PR
#3740 partially

### CODE REVIEW

**Comment by plroebuck** [comment]
Curious on your thoughts -- outside scope of this PR. Think there's any value to adding a `type` field to `Pending` where values would be one of: `sync`, `async`, or `promise`? You're more experienced with that aspect of the code.

**Comment by juergba** [comment]
Yes, I was thinking about extending `Pending` with additional properties, like error code or the hook causing the pending-error. I don't know yet, I'm still working on it.
I'm worried about the async version of this.skip(), it has not been working before, now getting worse as a mixture of uncaught error and multiple done calls. (The async skip() already includes a done call.)
Promises? I have just seen `sync` and `async` so far. I will have a look.

File: lib/runner.js [hunk 1]
```diff
@@ -634,7 +640,12 @@ Runner.prototype.runTests = function(suite, fn) {
           self.emit(constants.EVENT_TEST_PENDING, test);
         }
         self.emit(constants.EVENT_TEST_END, test);
-        return next();
+        if (err instanceof Pending) {
```
Comment (juergba) [inline lib/runner.js]: I'm not sure wether this if() check is really needed.

File: lib/runner.js [hunk 2]
```diff
@@ -634,7 +640,12 @@ Runner.prototype.runTests = function(suite, fn) {
...
+          self.suite = errSuite;
```
Comment (juergba) [inline lib/runner.js]: This line is unnice, but the same technique is used already above in line549.
IMO, by just changing one property the runner gets inconsistent.

**Comment by juergba** [comment]
@boneskull please tell me wether it makes sense to continue with this PR. Thanks.

**Comment by boneskull** [comment]
@juergba 	I think what you're proposing sounds good.
Would also like to hear your thoughts about whether this can land in a patch release.

**Comment by boneskull** [comment]
I've been ignoring this because of the "WIP" in the title.  If it's ready to review, please let me know.

**Comment by juergba** [comment]
Patch release is risky. IMO it certainly is a bug fix, but there have been very few (one?) opened issue about this topic. Either users don't use `this.skip()` frequently or they are happy with the current hook pattern. I suggest at least minor release.

Anyway there are more hook pattern fixes to come, for `this.skip()` in  `it()` and `afterEach()`.

Please review, it works, but I need to be confirmed with one or two doubts.

**Comment by boneskull** [comment]
I think this needs to be semver-major then

**Comment by dasilvacontin** [comment]
I'm thoroughly reviewing this one. It's taking me a bit due to having stepped away from the code for a while, and because our vars / function names are not very friendly (in runner.js, at least).

**Comment by mrstux** [comment]
FWIW, this is a major issue for us. We are trying to find a solution, but other than forking mocha and fixing the bug, we're not sure what to do.

We have beforeEach functions which acquire resources, and we have afterEach(done) functions which release them. The tests are predicated on the assumption that if a beforeEach runs, and there is an afterEach, then it will be run, whether the test passes, fails or is skipped.

End of story.

If the afterEach is not run because a test is skipped via this.skip(), then the resources will not be cleaned up, and tests will eventually cascade fail.

I know this is not what this exact PR is about, but you were wondering why you haven't had any other issues reported. Most likely because there is a very good issue, which documents the exact issue, and has a number of PRs in progress. Its only when you dig into the PR that you find some debate about when or if to actually release the fix.

Yes, this will possibly be a "breaking fix", and yes, you may want to update the major semver. your call :)

But please fix!

**Comment by juergba** [comment]
@mrstux It would be awesome if you could do some test runs with this branch.

@boneskull @craigtaub @outsideris 
I will merge this branch within the next two/three weeks. I would like to have this PR published with v7.0.0.

File: lib/runner.js (hunk 1 above)
Comment (juergba) [reply lib/runner.js]: It's not needed, reviewed by myself, outdated anyway.

File: lib/runner.js (hunk 2 above)
Comment (juergba) [reply lib/runner.js]: I improved this part, it's the same pattern used by failing `beforeEach` hooks. 
Reviewed by myself.

**Comment by juergba** [comment]
@HarshaNalluru I would highly appreciate some feedback on this PR. Could you do some test runs with this branch?

**Comment by HarshaNalluru** [comment]
> afterEach hooks of the same/higher suite level than the skipping one should run ("Z").

This .skip() behaviour seems to be more appropriate. 
Just tested this branch, works as expected. Thanks a lot for fixing this!! 🧡

**Comment by juergba** [comment]
@HarshaNalluru thank you! 👍
