### PR TITLE
Fixing errors that prevent mocha.js from loading in the browser - fixes #1558

### LINKED ISSUE #1558: Uncaught ReferenceError: Buffer is not defined [mocha.js:5833]
Getting this error with the latest version of the `mocha.js` file. I'm using the browser interface. Looks like the line that causes this error was added in eab389f3f106290e8386520a2f3b8206c18c486e. I set up a [dummy app](http://github.com/dustinbrownman/test-mochajs) demonstrate the error. Just open up `spec-runner.html` and open up the developer tools. Any thoughts on how to fix this? (Thanks to @clemf for finding this)

### PR DESCRIPTION
**Pull request by callmevlad**
Fixing a few issues caused by recent commits that break when mocha.js is loaded in the browser:

https://github.com/mochajs/mocha/commit/eab389f3f106290e8386520a2f3b8206c18c486e introduced `require('supports-color')`, which is not available in the browser.

https://github.com/mochajs/mocha/commit/00ef54cd41d46b1c29358942dc0874e2ae7da0ff added `if(Buffer && ...)` usage, which doesn't work in browsers.

### CODE REVIEW

**Comment by dasilvacontin** [comment]
:+1:

File: mocha.js [hunk 1]
```diff
@@ -1999,10 +1999,10 @@ var isatty = tty.isatty(1) && tty.isatty(2);
 exports = module.exports = Base;
 
 /**
- * Enable coloring by default.
+ * Enable coloring by default, except in the browser interface.
  */
 
-exports.useColors = supportsColor || (process.env.MOCHA_COLORS !== undefined);
+exports.useColors = process.env ? (supportsColor || (process.env.MOCHA_COLORS !== undefined)) : false;
```
Comment (a8m) [inline mocha.js]: **style issue:** this line too long(102 chars), imo you should stay with same code-style
e.g: [1](https://github.com/mochajs/mocha/blob/master/lib/reporters/base.js#L111-L114), [2](https://github.com/mochajs/mocha/blob/master/lib/utils.js#L442-L444)

File: mocha.js [hunk 2]
```diff
@@ -5845,7 +5845,7 @@ var isArray = Array.isArray || function (obj) {
  * Buffer.prototype.toJSON polyfill
  * @type {Function}
  */
-if(Buffer && Buffer.prototype) {
+if(typeof Buffer !== 'undefined' && Buffer.prototype) {
```
Comment (a8m) [inline mocha.js]: LGTM, see #1558

**Comment by travisjeffery** [comment]
fyi to all new collaborators, changes always need to happen outside of mocha.js. the mocha.js is compiled and the next time someone built it these changes would get blown away

**Comment by boneskull** [comment]
@callmevlad That means you'll need to change this PR to update the source files, not `mocha.js` itself.

File: mocha.js (hunk 1 above)
Comment (travisjeffery) [inline mocha.js]: i don't think you need to check this either since supportsColor will be null/undefined anyway

Comment (travisjeffery) [inline mocha.js]: this logic could also be done as 

`process.env && (supportsColor || (process.env.MOCHA_COLORS !== undefined)`

Comment (callmevlad) [inline mocha.js]: Thanks! Just a quick question - is `process.env` the correct way to detect whether we're in a non-browser environment? Not sure if `isatty` is what I should be keying off of...

File: mocha.js (hunk 2 above)
Comment (callmevlad) [inline mocha.js]: Doh, rookie mistake, will fix.

File: mocha.js (hunk 1 above)
Comment (a8m) [inline mocha.js]: [browser/isatty](https://github.com/mochajs/mocha/blob/master/lib/browser/tty.js#L2) no.
mm.. I'll take a look

Comment (travisjeffery) [inline mocha.js]: no, and i don't think you need to change this check. cause supportsColor will be null/undefined and process.env.MOCHA_COLORS will definitely be undefined.

**Comment by callmevlad** [comment]
@travisjeffery Apologies for the rookie mistake :-\

@boneskull Just pushed updated code with recommended changes.

**Comment by travisjeffery** [comment]
@callmevlad np! that was more for the other new collaborators who've been working on mocha for longer

File: lib/reporters/base.js [hunk 3]
```diff
@@ -31,10 +31,12 @@ var isatty = tty.isatty(1) && tty.isatty(2);
 exports = module.exports = Base;
 
 /**
- * Enable coloring by default.
+ * Enable coloring by default, except in the browser interface.
  */
 
-exports.useColors = supportsColor || (process.env.MOCHA_COLORS !== undefined);
+exports.useColors = process.env
```
Comment (travisjeffery) [inline lib/reporters/base.js]: i don't think you need this check here since by your check at line 9, `supportsColor` will be undefined/null

Comment (callmevlad) [inline lib/reporters/base.js]: If `supportsColor` is false, it falls through to the next check, and in the browser `process.env` is undefined so `process.env.MOCHA_COLORS` fails.

**Comment by dasilvacontin** [comment]
Yeah, like me. I need to be more careful reviewing PRs.

**Comment by dasilvacontin** [comment]
Bear in mind that, in the browser, `process.env` throws `ReferenceError: process is not defined`.

**Comment by dasilvacontin** [comment]
Never mind, I didn't know about the node shims at https://github.com/mochajs/mocha/blob/master/mocha.js#L6328-L6330
