### PR TITLE
Watch for test files are crashed

### LINKED ISSUE #4580: Watcher crashes when reloading code that throws (regression mocha@7 to mocha@8)
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend that you _not_ install Mocha globally.

### Description

MCVE: please see https://github.com/marcelbeumer/mocha-8-watcher-issue for a minimal test case with STR.

Since mocha@8 the watcher crashes when reloading tests and a require fails, for example when causing a syntax error. Errors that happen during test execution are handled correctly by the watcher. Experimenting with different mocha versions, it turns out it is a regression from v7 to v8.

### Steps to Reproduce

See MCVE: https://github.com/marcelbeumer/mocha-8-watcher-issue. It seems that when the watcher is reloading code that will throw when requiring, the watcher crashes.

**Expected behavior:**

The watcher does not crash when reloading test code. Behavior for the initial test run when starting the watcher is debatable but would be best if it handled both cases well.

**Actual behavior:** 

The watcher crashes when reloading test code that causes an error.

**Reproduces how often:** 

100%

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 8.30 (but also tried @8.0, and @7)
- The output of `node --version`: v15.6.0
- Your operating system
  - name and version: macOS 11.1
  - architecture (32 or 64-bit): 64
- Your shell (e.g., bash, zsh, PowerShell, cmd): zsh
- Your browser and version (if running browser tests):
- Any third-party Mocha-related modules (and their versions):
- Any code transpiler (e.g., TypeScript, CoffeeScript, Babel) being used (and its version): no, but same behavior with ts-node setup (see branch in https://github.com/marcelbeumer/mocha-8-watcher-issue)

### PR DESCRIPTION
**Pull request by outsideris**
### Description of the Change
In watch mode, the watcher crashed when there are syntax errors in test files during `require('test file')`.
It only happens in serial mode and Node v15+.

This `try - catch` statement removed [when we introduce parallel mode](https://github.com/mochajs/mocha/commit/2078c3203f55ee0e1783dc2fc9e20ac51dcb6896#diff-14a1e3aa193d6f208b9ffdfeec1876f2cbc0e51007d061a87644e9ea9df59676L94).
I think we need `try - catch` here.

And I added test cases for the crash case to prevent regression.

### Why should this be in core?
Watching should be worked.

### Benefits
Users can use watch mode when the test code is broken.

### Applicable issues
Fix #4580

### CODE REVIEW

File: test/integration/helpers.js [hunk 1]
```diff
@@ -470,6 +470,7 @@ async function runMochaWatchJSONAsync(args, opts, change) {
       // eslint-disable-next-line no-control-regex
       .replace(/\u001b\[\?25./g, '')
       .split('\u001b[2K')
+      .filter(x => x)
```
Comment (outsideris) [inline test/integration/helpers.js:473]: I filtered output because the output is an empty string(`''`) when a test file is crashed.

File: test/integration/options/watch.spec.js [hunk 2]
```diff
@@ -47,6 +47,23 @@ describe('--watch', function() {
       });
     });
 
+    it('reruns test when watched test file is crashed', function() {
```
Comment (juergba) [inline test/integration/options/watch.spec.js:50]: reruns test when watched test file ~~is crashed~~ crashes

File: test/integration/options/watch.spec.js [hunk 3]
```diff
@@ -47,6 +47,23 @@ describe('--watch', function() {
...
+        replaceFileContents(testFile, 'done();', 'done((;');
+      })
+        .then(() => {
+          return runMochaWatchJSONAsync([testFile], tempDir, () => {
+            replaceFileContents(testFile, 'done((;', 'done();');
+          });
+        })
+        .then(results => {
+          expect(results, 'to have length', 1);
+        });
```
Comment (juergba) [inline test/integration/options/watch.spec.js:64]: It's not necessary to call `runMochaWatchJSONAsync`  twice. You don't process the result of the first call (good, then bad test) anyway. `results` contains only the second call (bad, then good test).

The following runs first the bad, then the good test with only one call:
```js
it('reruns test when watched test file crashes', function() {
      const testFile = path.join(tempDir, 'test.js');
      copyFixture(DEFAULT_FIXTURE, testFile);

      replaceFileContents(testFile, 'done();', 'done((;');

      return runMochaWatchJSONAsync([testFile], tempDir, () => {
        replaceFileContents(testFile, 'done((;', 'done();');
      })
        .then(results => {
          expect(results, 'to have length', 1);
        });
    });
```

File: test/integration/options/watch.spec.js [hunk 4]
```diff
@@ -58,6 +75,23 @@ describe('--watch', function() {
...
+          replaceFileContents(testFile, 'done();', 'done((;');
+        })
+          .then(() => {
+            return runMochaWatchJSONAsync([testFile], tempDir, () => {
+              replaceFileContents(testFile, 'done((;', 'done();');
+            });
+          })
+          .then(results => {
+            expect(results, 'to have length', 1);
+          });
```
Comment (juergba) [inline test/integration/options/watch.spec.js:93]: same

**Review by juergba — COMMENTED** [review]
Your bug fix lgtm, but the tests are a little weird.

File: test/integration/options/watch.spec.js (hunk 3 above)
Comment (outsideris) [reply test/integration/options/watch.spec.js:64]: Smart approach!!

**Comment by outsideris** [comment]
Fixed

**Review by juergba — COMMENTED** [review]
I forgot to approve this PR. Yes, approved.
