### PR TITLE
fix: handle case of invalid package.json with no explicit config

### LINKED ISSUE #5141: 🐛 Bug: mocha fails silently on invalid `package.json` section
### Bug Report Checklist

- [X] I have read and agree to Mocha's [Code of Conduct](https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/mochajs/mocha/blob/master/.github/CONTRIBUTING.md)
- [X] I have searched for [related issues](https://github.com/mochajs/mocha/issues?q=is%3Aissue) and [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20), but none matched my issue.
- [X] I have 'smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, my usage of Mocha, or Mocha itself.
- [X] I want to provide a PR to resolve this

### Expected

I made an error in my `package.json` (an extra comma) because JSON is a bad format for configuration files ;-) like this:
```json
"mocha": {
    "spec": "./*.spec.js",
}
```
I expected `mocha` to give me an error, ideally a bit friendlier than the one from `npm`, but something like that:
```
$ npm install
npm ERR! code EJSONPARSE
...
npm ERR! JSON.parse Note: package.json must be actual JSON, not just JavaScript.
```

### Actual

Mocha just failed as if I hadn't configured it at all.  This was very confusing:
```
$ npx mocha
Error: No test files found: "test"
```

### Minimal, Reproducible Example

See "expected" above but basically:
```
npm install -D mocha
```
then add the offending section to `package.json`, then create `foo.spec.js`, then try to run `mocha`.

### Versions

`
10.4.0
10.4.0
v20.11.0
`

### Additional Info

I could definitely provide a PR if you could direct me to the appropriate place in the code (with which I am not familiar)

### PR DESCRIPTION
**Pull request by dhdaines**
## PR Checklist

- [x] Addresses an existing open issue: fixes #5141
- [x] That issue was marked as [`status: accepting prs`](https://github.com/mochajs/mocha/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/mochajs/mocha/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Handle the corner case which can happen if:

- You had a perfectly good `package.json` which npm was happy with
- You decided to put `mocha` configuration inside your `package.json`
- You left a stray comma in there, because you are used to more sensible configuration file formats ;-)
- Instead of running `npm test` you ran `mocha` directly (with `npx` or just `mocha.js`)

As detailed here: https://github.com/dhdaines/mocha-5141

### CODE REVIEW

**Comment by dhdaines** [comment]
(signed the CLA!)

File: lib/cli/options.js [hunk 1]
```diff
@@ -195,6 +195,11 @@ const loadPkgRc = (args = {}) => {
           `Unable to read/parse ${filepath}: ${err}`,
           filepath
         );
+      } else if (err.toString().includes('SyntaxError')) {
+        throw createUnparsableFileError(
```
Comment (voxpelli) [inline lib/cli/options.js:199]: (On my phone) Will throwing here result in a warning? Feels more like an error to me?

File: lib/cli/options.js [hunk 2]
```diff
@@ -195,6 +195,11 @@ const loadPkgRc = (args = {}) => {
           `Unable to read/parse ${filepath}: ${err}`,
           filepath
         );
+      } else if (err.toString().includes('SyntaxError')) {
```
Comment (voxpelli) [inline lib/cli/options.js:198]: If we want to separate the parsing from the reading errors, then I would suggest instead splitting this try/catch into an initial one for reading followed by a second one for parsing – that way we will not have to check the error as we know it's `JSON.parse()` that fails

Also gives more granular error for the existing use case – different error message depending on whether it can't read or can't parse

**Comment by voxpelli** [comment]
Thanks for the PR! Gave some feedback

File: lib/cli/options.js (hunk 2 above)
Comment (dhdaines) [reply lib/cli/options.js:198]: Seems like a good idea.  Also, would it be useful to give an error for parsing errors more like the one npm gives, i.e. "make sure your package.json is JSON and not Javascript"?

Comment (voxpelli) [reply lib/cli/options.js:198]: I don’t think it’s needed, just a warning saying “could not check package.json due to error while parsing” is probably the clearest

File: lib/cli/options.js (hunk 1 above)
Comment (dhdaines) [reply lib/cli/options.js:199]: It will fail with an error, these exceptions are not caught (we could, possibly, catch them at the top level of the CLI and exit cleanly in order to avoid barfing stack traces on the user...)

File: lib/cli/options.js (hunk 2 above)
Comment (dhdaines) [reply lib/cli/options.js]: I've simply split it into "Unable to read" and "Unable to parse" for the moment, not sure if there is a better wording.

Comment (JoshuaKGoldberg) [reply lib/cli/options.js]: Looks great to me 🙂 I like it!

File: test/node-unit/cli/options.spec.js [hunk 3]
```diff
@@ -199,6 +199,37 @@ describe('options', function () {
...
 
+        describe('when path to package.json unspecified and package.json exists but is invalid', function () {
+          beforeEach(function () {
+            const filepath = '/some/package.json';
+            readFileSync = sinon.stub();
+            // package.json
+            readFileSync
+              .onFirstCall()
+              // Note the extra comma
+              .returns('{"mocha": {"retries": 3, "_": ["foobar.spec.js"],}}');
```
Comment (JoshuaKGoldberg) [inline test/node-unit/cli/options.spec.js:210]: [Testing] Nit: no need to have a difficult-to-read JSON that needs a comment, when we can have something more straightforward:

```suggestion
              .returns('{definitely-invalid');
```

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, nicely done! Agreed with the strategy inside 👍 thanks!

Since @voxpelli was looking at this before, leaving open for re-review.

**Comment by JoshuaKGoldberg** [comment]
Btw @dhdaines, just a heads up, the `- [ x ]`s in the description can be `- [x]`s (no spacing) to work with [GitHub's task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists). I edited them just now. 🙂

**Comment by dhdaines** [comment]
> Btw @dhdaines, just a heads up, the `- [ x ]`s in the description can be `- [x]`s (no spacing) to work with [GitHub's task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists). I edited them just now. 🙂

Ohhh!  Thank you, I have been wondering about that for ages now! (suppose I should have RTF the Markdown manual...)

File: test/node-unit/cli/options.spec.js (hunk 3 above)
Comment (dhdaines) [reply test/node-unit/cli/options.spec.js:210]: Ah, yes, that is a lot clearer (the most common error people will make in JSON is obviously the trailing comma, but that isn't very relevant for this test case)

**Comment by dhdaines** [comment]
Ah, I suspect that the more obviously invalid JSON will break the too-specific assertion in the test...  will fix it in a second.

**Comment by dhdaines** [comment]
> Ah, I suspect that the more obviously invalid JSON will break the too-specific assertion in the test... will fix it in a second.

Done!

**Review by JoshuaKGoldberg — APPROVED** [review]
🙌 Looks great to me! Just waiting on @voxpelli. Thanks!
